// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rktrjxiwcqhrhzhtqfli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrdHJqeGl3Y3Focmh6aHRxZmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MzA2MjUsImV4cCI6MjA1NTQwNjYyNX0.g7H34sTnY2u7Xm8tGIlIcOWII1r7onIvwFpganxNW1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);